<?php

declare(strict_types=1);

namespace Vyse\Installer\Task;

use Composer\IO\IOInterface;
use Composer\Util\Filesystem;
use Vyse\Installer\Data\Config;
use Vyse\Installer\Interface\TaskInterface;

class HookRunnerTask implements TaskInterface
{
    public function __invoke(
        Config $config,
        IOInterface $io,
        string $projectRoot,
    ): void {
        if (!$config->hasHooks()) {
            return;
        }

        $fs = new Filesystem();
        $targetDir = $projectRoot . '/vyse/hooks';

        // Ensure clean slate
        if (is_dir($targetDir)) {
            $fs->removeDirectory($targetDir);
        }
        $fs->ensureDirectoryExists($targetDir);

        $installedCount = 0;

        foreach ($config->getHooks() as $event => $scripts) {
            ksort($scripts);

            $targetPath = $targetDir . '/' . $event;
            $bashScript = $this->buildRunnerScript($event, $scripts);

            file_put_contents($targetPath, $bashScript);
            chmod($targetPath, 0755);

            $installedCount++;
        }

        if ($installedCount > 0) {
            $io->write("<info>[Vyse] Compiled {$installedCount} hook runners into ./vyse/hooks/.</info>");
        }
    }

    /**
     * @param array<string, string> $scripts
     */
    private function buildRunnerScript(
        string $event,
        array $scripts,
    ): string {
        $bash = <<<BASH
#!/usr/bin/env bash
# ==============================================================================
# Auto-generated by Vyse. Do not edit manually.
# Event: {$event}
# ==============================================================================
set -e


BASH;

        foreach ($scripts as $name => $script) {
            $bash .= <<<BASH
echo "[Vyse] Running hook: {$name}..."
{$script}


BASH;
        }

        return $bash;
    }
}
